import { useChatStore } from '@/store/chatStore';
import { usePlayerStore } from '@/store/playerStore';
import { useState } from 'react';

export default function ChatComposer() {
  const activeChannel = useChatStore((state) => state.activeChannel);
    const sendComplexoMessage = useChatStore((state) => state.sendComplexoMessage);
      const sendFaccaoMessage = useChatStore((state) => state.sendFaccaoMessage);
        const sendMailMessage = useChatStore((state) => state.sendMailMessage);

          const player = usePlayerStore((state) => state.player);

            const [body, setBody] = useState('');
              const [subject, setSubject] = useState('');
                const [recipientId, setRecipientId] = useState('');
                  const [recipientName, setRecipientName] = useState('');

                    const senderId = player?._id || 'local-player';
                      const senderName = player?.name || 'Sem nome';

                        const handleSend = () => {
                            if (!body.trim()) return;

                                if (activeChannel === 'complexo') {
                                      sendComplexoMessage({
                                              senderId,
                                                      senderName,
                                                              body: body.trim(),
                                                                    });
                                                                          setBody('');
                                                                                return;
                                                                                    }

                                                                                        if (activeChannel === 'faccao') {
                                                                                              const factionId = (player as any)?.faction?.factionId || '';
                                                                                                    if (!factionId) return;

                                                                                                          sendFaccaoMessage({
                                                                                                                  senderId,
                                                                                                                          senderName,
                                                                                                                                  factionId,
                                                                                                                                          body: body.trim(),
                                                                                                                                                });
                                                                                                                                                      setBody('');
                                                                                                                                                            return;
                                                                                                                                                                }

                                                                                                                                                                    if (!recipientId.trim() || !recipientName.trim()) return;

                                                                                                                                                                        sendMailMessage({
                                                                                                                                                                              senderId,
                                                                                                                                                                                    senderName,
                                                                                                                                                                                          recipientId: recipientId.trim(),
                                                                                                                                                                                                recipientName: recipientName.trim(),
                                                                                                                                                                                                      subject: subject.trim(),
                                                                                                                                                                                                            body: body.trim(),
                                                                                                                                                                                                                });

                                                                                                                                                                                                                    setBody('');
                                                                                                                                                                                                                        setSubject('');
                                                                                                                                                                                                                            setRecipientId('');
                                                                                                                                                                                                                                setRecipientName('');
                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                        <div className="space-y-3 rounded-3xl border border-white/10 bg-black/40 p-4">
                                                                                                                                                                                                                                              {activeChannel === 'mail' && (
                                                                                                                                                                                                                                                      <>
                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                            value={recipientName}
                                                                                                                                                                                                                                                                                        onChange={(e) => setRecipientName(e.target.value)}
                                                                                                                                                                                                                                                                                                    placeholder="Nome do destinatário"
                                                                                                                                                                                                                                                                                                                className="w-full rounded-2xl bg-zinc-900 px-4 py-3 text-white outline-none"
                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                value={recipientId}
                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setRecipientId(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                        placeholder="ID do destinatário"
                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-2xl bg-zinc-900 px-4 py-3 text-white outline-none"
                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                    value={subject}
                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setSubject(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Assunto"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full rounded-2xl bg-zinc-900 px-4 py-3 text-white outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={body}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setBody(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        activeChannel === 'complexo'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? 'Fale com todo o Complexo...'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : activeChannel === 'faccao'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? 'Fale com a sua facção...'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : 'Escreva sua mensagem...'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="min-h-[120px] w-full rounded-2xl bg-zinc-900 px-4 py-3 text-white outline-none resize-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={handleSend}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full rounded-2xl bg-emerald-500 px-4 py-4 font-black text-black"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Enviar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
