import type {
  GangCTState,
  GangMemberDefinition,
  GangMemberType,
} from '@/types/gangWar';

export const GANG_MAX_MEMBER_LEVEL = 10;
export const GANG_BASE_CAPACITY = 12;
export const GANG_CT_MAX_LEVEL = 10;

export const DEFAULT_GANG_CT_STATE: GangCTState = {
  level: 1,
  maxLevel: GANG_CT_MAX_LEVEL,
  trainingSlots: 1,
  recoveryBonusPercent: 0,
  trainingSpeedBonusPercent: 0,
  gangCapacityBonus: 0,
};

export const GANG_MEMBER_DEFINITIONS: Record<GangMemberType, GangMemberDefinition> = {
  capanga: {
    type: 'capanga',
    label: 'Capanga',
    description: 'Base numérica da firma. Sustenta o volume do confronto.',
    role: 'linha_de_frente',
    recruitBaseCostDirtyMoney: 1200,
    trainingBaseCostDirtyMoney: 700,
    maintenanceBaseCostDirtyMoney: 180,
    trainingBaseHours: 2,
    casualtyWeight: 1.05,
    battlePriority: 10,
    baseStats: { rajada: 7, blindagem: 6, folego: 7, quebra: 6 },
    special: {},
  },
  frente: {
    type: 'frente',
    label: 'Frente',
    description: 'Linha de entrada do ataque.',
    role: 'linha_de_frente',
    recruitBaseCostDirtyMoney: 1800,
    trainingBaseCostDirtyMoney: 950,
    maintenanceBaseCostDirtyMoney: 240,
    trainingBaseHours: 3,
    casualtyWeight: 1.15,
    battlePriority: 9,
    baseStats: { rajada: 9, blindagem: 6, folego: 8, quebra: 7 },
    special: {},
  },
  executor: {
    type: 'executor',
    label: 'Executor',
    description: 'Unidade de finalização pesada.',
    role: 'linha_de_frente',
    recruitBaseCostDirtyMoney: 2600,
    trainingBaseCostDirtyMoney: 1400,
    maintenanceBaseCostDirtyMoney: 320,
    trainingBaseHours: 4,
    casualtyWeight: 1.1,
    battlePriority: 8,
    baseStats: { rajada: 9, blindagem: 6, folego: 7, quebra: 9 },
    special: {},
  },
  assassino: {
    type: 'assassino',
    label: 'Assassino',
    description: 'Ofensiva letal e precisa.',
    role: 'tatico',
    recruitBaseCostDirtyMoney: 3200,
    trainingBaseCostDirtyMoney: 1700,
    maintenanceBaseCostDirtyMoney: 380,
    trainingBaseHours: 4,
    casualtyWeight: 1.25,
    battlePriority: 7,
    baseStats: { rajada: 10, blindagem: 4, folego: 6, quebra: 9 },
    special: {},
  },
  muralha: {
    type: 'muralha',
    label: 'Muralha',
    description: 'Tanque da gangue.',
    role: 'linha_de_frente',
    recruitBaseCostDirtyMoney: 3000,
    trainingBaseCostDirtyMoney: 1600,
    maintenanceBaseCostDirtyMoney: 360,
    trainingBaseHours: 4,
    casualtyWeight: 0.8,
    battlePriority: 6,
    baseStats: { rajada: 4, blindagem: 10, folego: 10, quebra: 4 },
    special: {},
  },
  certeiro: {
    type: 'certeiro',
    label: 'Certeiro',
    description: 'Precisão ofensiva.',
    role: 'tatico',
    recruitBaseCostDirtyMoney: 2800,
    trainingBaseCostDirtyMoney: 1500,
    maintenanceBaseCostDirtyMoney: 330,
    trainingBaseHours: 4,
    casualtyWeight: 1.15,
    battlePriority: 7,
    baseStats: { rajada: 9, blindagem: 4, folego: 6, quebra: 7 },
    special: {},
  },
  motorista: {
    type: 'motorista',
    label: 'Motorista',
    description: 'Mobilidade e reposicionamento.',
    role: 'tatico',
    recruitBaseCostDirtyMoney: 2300,
    trainingBaseCostDirtyMoney: 1300,
    maintenanceBaseCostDirtyMoney: 290,
    trainingBaseHours: 3,
    casualtyWeight: 1,
    battlePriority: 6,
    baseStats: { rajada: 6, blindagem: 6, folego: 7, quebra: 7 },
    special: { mobilityPower: 8 },
  },
  nitro: {
    type: 'nitro',
    label: 'Nitro',
    description: 'Explosão ofensiva e aceleração.',
    role: 'tatico',
    recruitBaseCostDirtyMoney: 2500,
    trainingBaseCostDirtyMoney: 1350,
    maintenanceBaseCostDirtyMoney: 300,
    trainingBaseHours: 3,
    casualtyWeight: 1.1,
    battlePriority: 6,
    baseStats: { rajada: 8, blindagem: 4, folego: 6, quebra: 6 },
    special: { mobilityPower: 6 },
  },
  armeiro: {
    type: 'armeiro',
    label: 'Armeiro',
    description: 'Sustenta o poder de fogo da firma.',
    role: 'tatico',
    recruitBaseCostDirtyMoney: 2600,
    trainingBaseCostDirtyMoney: 1400,
    maintenanceBaseCostDirtyMoney: 310,
    trainingBaseHours: 3,
    casualtyWeight: 1,
    battlePriority: 5,
    baseStats: { rajada: 6, blindagem: 5, folego: 6, quebra: 8 },
    special: { weaponPower: 9 },
  },
  informante: {
    type: 'informante',
    label: 'Informante',
    description: 'Leitura tática e visão da rua.',
    role: 'tatico',
    recruitBaseCostDirtyMoney: 2400,
    trainingBaseCostDirtyMoney: 1250,
    maintenanceBaseCostDirtyMoney: 280,
    trainingBaseHours: 3,
    casualtyWeight: 1.2,
    battlePriority: 5,
    baseStats: { rajada: 5, blindagem: 4, folego: 6, quebra: 5 },
    special: { intelPower: 10 },
  },
  wifi: {
    type: 'wifi',
    label: 'WiFi',
    description: 'Coordenação e comunicação do bonde.',
    role: 'tatico',
    recruitBaseCostDirtyMoney: 2200,
    trainingBaseCostDirtyMoney: 1200,
    maintenanceBaseCostDirtyMoney: 260,
    trainingBaseHours: 3,
    casualtyWeight: 1.15,
    battlePriority: 4,
    baseStats: { rajada: 3, blindagem: 4, folego: 6, quebra: 3 },
    special: { coordinationPower: 10 },
  },
  medico: {
    type: 'medico',
    label: 'Médico',
    description: 'Converte perdas definitivas em feridos.',
    role: 'suporte',
    recruitBaseCostDirtyMoney: 3400,
    trainingBaseCostDirtyMoney: 1800,
    maintenanceBaseCostDirtyMoney: 400,
    trainingBaseHours: 4,
    casualtyWeight: 0.95,
    battlePriority: 4,
    baseStats: { rajada: 2, blindagem: 4, folego: 9, quebra: 2 },
    special: { medicalPower: 12 },
  },
  lavador: {
    type: 'lavador',
    label: 'Lavador',
    description: 'Sustentação financeira da tropa.',
    role: 'economico',
    recruitBaseCostDirtyMoney: 2800,
    trainingBaseCostDirtyMoney: 1450,
    maintenanceBaseCostDirtyMoney: 290,
    trainingBaseHours: 3,
    casualtyWeight: 1.05,
    battlePriority: 3,
    baseStats: { rajada: 2, blindagem: 4, folego: 7, quebra: 2 },
    special: { economyPower: 10 },
  },
  ladrao: {
    type: 'ladrao',
    label: 'Ladrão',
    description: 'Especialista em saque e retorno do ataque.',
    role: 'economico',
    recruitBaseCostDirtyMoney: 2100,
    trainingBaseCostDirtyMoney: 1150,
    maintenanceBaseCostDirtyMoney: 240,
    trainingBaseHours: 3,
    casualtyWeight: 1.1,
    battlePriority: 4,
    baseStats: { rajada: 5, blindagem: 4, folego: 6, quebra: 5 },
    special: { lootPower: 10 },
  },
  negociador: {
    type: 'negociador',
    label: 'Negociador',
    description: 'Reduz custo, melhora acordo e favorece a firma.',
    role: 'suporte',
    recruitBaseCostDirtyMoney: 2600,
    trainingBaseCostDirtyMoney: 1350,
    maintenanceBaseCostDirtyMoney: 280,
    trainingBaseHours: 3,
    casualtyWeight: 1.05,
    battlePriority: 3,
    baseStats: { rajada: 2, blindagem: 5, folego: 6, quebra: 2 },
    special: { negotiationPower: 10 },
  },
};

export function getGangMemberDefinition(type: GangMemberType): GangMemberDefinition {
  return GANG_MEMBER_DEFINITIONS[type];
}

export function getCTStateFromLevel(level: number): GangCTState {
  const safeLevel = Math.max(1, Math.min(GANG_CT_MAX_LEVEL, Number(level || 1)));

  return {
    level: safeLevel,
    maxLevel: GANG_CT_MAX_LEVEL,
    trainingSlots: 1 + Math.floor((safeLevel - 1) / 2),
    recoveryBonusPercent: (safeLevel - 1) * 4,
    trainingSpeedBonusPercent: (safeLevel - 1) * 5,
    gangCapacityBonus: (safeLevel - 1) * 4,
  };
}