import { create } from 'zustand';

const STORAGE_KEY = 'playerData';

type Player = {
  balances: {
      dirtyMoney: number;
          cleanMoney: number;
              corre: number;
                };
                  inventory: any[];
                    progression: {
                        level: number;
                            power: number;
                                pageLevels: Record<string, number>;
                                  };
                                    skills: {
                                        attack: number;
                                            defense: number;
                                                intelligence: number;
                                                    agility: number;
                                                        respect: number;
                                                            vigor: number;
                                                              };
                                                              };

                                                              type PlayerStore = {
                                                                player: Player;
                                                                  isSyncing: boolean;
                                                                    error: string | null;

                                                                      // CORE
                                                                        loadPlayer: () => void;
                                                                          setPlayer: (player: Player) => void;
                                                                            saveLocal: () => void;

                                                                              // BALANCES
                                                                                addDirtyMoney: (amount: number) => void;
                                                                                  removeDirtyMoney: (amount: number) => void;
                                                                                    removeDirtyMoneyPercent: (percent: number) => void;

                                                                                      addCleanMoney: (amount: number) => void;
                                                                                        removeCleanMoney: (amount: number) => void;

                                                                                          addCorre: (amount: number) => void;
                                                                                            removeCorre: (amount: number) => void;

                                                                                              // INVENTORY
                                                                                                addItem: (item: any) => void;

                                                                                                  // PROGRESSION
                                                                                                    setLevel: (level: number) => void;
                                                                                                      setPower: (power: number) => void;
                                                                                                        setPageLevel: (page: string, level: number) => void;

                                                                                                          // SKILLS
                                                                                                            addSkill: (skill: keyof Player['skills'], value: number) => void;
                                                                                                              addSkillPercent: (skill: keyof Player['skills'], percent: number) => void;

                                                                                                                // BACKEND
                                                                                                                  sync: () => Promise<void>;
                                                                                                                  };

                                                                                                                  const initialPlayer: Player = {
                                                                                                                    balances: {
                                                                                                                        dirtyMoney: 1000,
                                                                                                                            cleanMoney: 0,
                                                                                                                                corre: 1000,
                                                                                                                                  },
                                                                                                                                    inventory: [],
                                                                                                                                      progression: {
                                                                                                                                          level: 1,
                                                                                                                                              power: 0,
                                                                                                                                                  pageLevels: {},
                                                                                                                                                    },
                                                                                                                                                      skills: {
                                                                                                                                                          attack: 0,
                                                                                                                                                              defense: 0,
                                                                                                                                                                  intelligence: 0,
                                                                                                                                                                      agility: 0,
                                                                                                                                                                          respect: 0,
                                                                                                                                                                              vigor: 0,
                                                                                                                                                                                },
                                                                                                                                                                                };

                                                                                                                                                                                export const usePlayerStore = create<PlayerStore>((set, get) => ({
                                                                                                                                                                                  player: initialPlayer,
                                                                                                                                                                                    isSyncing: false,
                                                                                                                                                                                      error: null,

                                                                                                                                                                                        loadPlayer: () => {
                                                                                                                                                                                            const stored = localStorage.getItem(STORAGE_KEY);
                                                                                                                                                                                                if (stored) {
                                                                                                                                                                                                      set({ player: JSON.parse(stored) });
                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                set({ player: initialPlayer });
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                      },

                                                                                                                                                                                                                        setPlayer: (player) => {
                                                                                                                                                                                                                            set({ player });
                                                                                                                                                                                                                                localStorage.setItem(STORAGE_KEY, JSON.stringify(player));
                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                    saveLocal: () => {
                                                                                                                                                                                                                                        const player = get().player;
                                                                                                                                                                                                                                            localStorage.setItem(STORAGE_KEY, JSON.stringify(player));
                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                // 💰 DIRTY MONEY
                                                                                                                                                                                                                                                  addDirtyMoney: (amount) => {
                                                                                                                                                                                                                                                      const player = get().player;
                                                                                                                                                                                                                                                          player.balances.dirtyMoney += amount;
                                                                                                                                                                                                                                                              set({ player });
                                                                                                                                                                                                                                                                  get().saveLocal();
                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                      removeDirtyMoney: (amount) => {
                                                                                                                                                                                                                                                                          const player = get().player;
                                                                                                                                                                                                                                                                              player.balances.dirtyMoney = Math.max(0, player.balances.dirtyMoney - amount);
                                                                                                                                                                                                                                                                                  set({ player });
                                                                                                                                                                                                                                                                                      get().saveLocal();
                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                          removeDirtyMoneyPercent: (percent) => {
                                                                                                                                                                                                                                                                                              const player = get().player;
                                                                                                                                                                                                                                                                                                  const loss = player.balances.dirtyMoney * (percent / 100);
                                                                                                                                                                                                                                                                                                      player.balances.dirtyMoney = Math.max(0, player.balances.dirtyMoney - loss);
                                                                                                                                                                                                                                                                                                          set({ player });
                                                                                                                                                                                                                                                                                                              get().saveLocal();
                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                  // 💎 CLEAN MONEY
                                                                                                                                                                                                                                                                                                                    addCleanMoney: (amount) => {
                                                                                                                                                                                                                                                                                                                        const player = get().player;
                                                                                                                                                                                                                                                                                                                            player.balances.cleanMoney += amount;
                                                                                                                                                                                                                                                                                                                                set({ player });
                                                                                                                                                                                                                                                                                                                                    get().saveLocal();
                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                        removeCleanMoney: (amount) => {
                                                                                                                                                                                                                                                                                                                                            const player = get().player;
                                                                                                                                                                                                                                                                                                                                                player.balances.cleanMoney = Math.max(0, player.balances.cleanMoney - amount);
                                                                                                                                                                                                                                                                                                                                                    set({ player });
                                                                                                                                                                                                                                                                                                                                                        get().saveLocal();
                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                            // ⚡ CORRE (GIROS)
                                                                                                                                                                                                                                                                                                                                                              addCorre: (amount) => {
                                                                                                                                                                                                                                                                                                                                                                  const player = get().player;
                                                                                                                                                                                                                                                                                                                                                                      player.balances.corre += amount;
                                                                                                                                                                                                                                                                                                                                                                          set({ player });
                                                                                                                                                                                                                                                                                                                                                                              get().saveLocal();
                                                                                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                                                                                  removeCorre: (amount) => {
                                                                                                                                                                                                                                                                                                                                                                                      const player = get().player;
                                                                                                                                                                                                                                                                                                                                                                                          player.balances.corre = Math.max(0, player.balances.corre - amount);
                                                                                                                                                                                                                                                                                                                                                                                              set({ player });
                                                                                                                                                                                                                                                                                                                                                                                                  get().saveLocal();
                                                                                                                                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                                                                                                                                      // 🎒 INVENTÁRIO
                                                                                                                                                                                                                                                                                                                                                                                                        addItem: (item) => {
                                                                                                                                                                                                                                                                                                                                                                                                            const player = get().player;
                                                                                                                                                                                                                                                                                                                                                                                                                player.inventory.push(item);
                                                                                                                                                                                                                                                                                                                                                                                                                    set({ player });
                                                                                                                                                                                                                                                                                                                                                                                                                        get().saveLocal();
                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                            // 📈 PROGRESSO
                                                                                                                                                                                                                                                                                                                                                                                                                              setLevel: (level) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                  const player = get().player;
                                                                                                                                                                                                                                                                                                                                                                                                                                      player.progression.level = level;
                                                                                                                                                                                                                                                                                                                                                                                                                                          set({ player });
                                                                                                                                                                                                                                                                                                                                                                                                                                              get().saveLocal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                                                                                                                                                  setPower: (power) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const player = get().player;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          player.progression.power = power;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              set({ player });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  get().saveLocal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setPageLevel: (page, level) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const player = get().player;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              player.progression.pageLevels[page] = level;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  set({ player });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      get().saveLocal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // 🧠 SKILLS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            addSkill: (skill, value) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const player = get().player;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player.skills[skill] += value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        set({ player });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            get().saveLocal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                addSkillPercent: (skill, percent) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const player = get().player;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        player.skills[skill] += player.skills[skill] * (percent / 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            set({ player });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                get().saveLocal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ☁️ SYNC COM BACKEND (Render)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sync: async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const player = get().player;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    set({ isSyncing: true });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await fetch('https://comando-backend.onrender.com/player/update', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  method: 'PATCH',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Content-Type': 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify(player),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                set({ isSyncing: false });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                set({ error: 'Erro ao sincronizar', isSyncing: false });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }));
