name: Build Check

on:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Wix CLI
        run: npm install -g @wix/cli

      - name: Instalar dependências (modo Wix)
        run: wix install

      - name: Build do projeto
        run: wix build